### PR TITLE
SRC attribute shouldn't be unescaped

### PR DESCRIPTION
**Pull request by benjaminclot**
See issue #98.

### CODE REVIEW

**Comment by benjaminclot** [comment]
The test failed because when writing a script src, one shouldn't have to escape ampersands. I'll propose a test update.

**Comment by jnewman** [comment]
Does this rebreak #81 ?

**Comment by benjaminclot** [comment]
No, because #81 was flawed: it tested the writing of a script with ampersands, which isn't the "right" way to do so. Hence my test.js update.

**Comment by benjaminclot** [comment]
Commenting out the two tests that should **never** happen in real life (as they will fail if you try to do this in "normal" mode) makes the build pass.

**Comment by jnewman** [comment]
Can you provide a failing test that passes w/ this pull? I'd be willing to give up on writing outerHTML, but I need to see a case that's actually broken.

**Comment by benjaminclot** [comment]
My latest changes include two tests that you can run standalone with a network observer open. You will see that parameters aren't correct in the current release, whereas they are in my PR.

In order to more clearly view the issue, here are two examples:
- http://codepen.io/anon/pen/azGpLN (master, not working)
- http://codepen.io/anon/pen/ZYoLXz (my PR, working)

**Comment by jnewman** [comment]
Please ads tests that fail before and pass with this change.

**Comment by debugwand** [comment]
this also fixes a problem i have been having with &param being converted to %B6m - is there a blocker to merging?

**Comment by jnewman** [comment]
Yes, this needs aa test

**Comment by sethyates** [comment]
We believe this is fixed in 2.0.0. Please retest against 2.0.0 release and open a new issue following Issue Reporting guidelines in 2.0.0 if you believe this is still an issue.

**Pull request closed without merging**
