### PR TITLE
FIX Bug with [conditional] HTML comments

### PR DESCRIPTION
**Pull request by francoismassart**
This branch, uses the latest version of postscribe code + a new version number (1.3.3) + unit tests for comments in HTML markup + FIX for #102

### CODE REVIEW

**Comment by davidbarratt** [comment]
@francoismassart,

Can you re-roll this against the latest `master` ?

Also, don't increment the version number, let the maintainer do that. :)

**Comment by jnewman** [comment]
Looks good, but yeah, I want to choose what goes in a release.

**Comment by davidbarratt** [comment]
@francoismassart,

Also, I believe the `dist` files get generated with grunt, so probably shouldn't modify those. :)

**Comment by sethyates** [comment]
We believe this is fixed in 2.0.0.  Please retest against 2.0.0 release and open a new issue following Issue Reporting guidelines in 2.0.0 if you believe this is still an issue.

**Pull request closed without merging**
