### PR TITLE
Upgrade vulnerable packages 

### PR DESCRIPTION
**Pull request by YoussefKaib**
Found 2 critical vulnerabilities 
[Growl](https://www.npmjs.com/advisories/146) 
[Open](https://nodesecurity.io/advisories/663)
```
found 88 vulnerabilities (32 low, 36 moderate, 18 high, 2 critical)
```

I have updated rest of packages except for manual review
```
found 29 vulnerabilities (6 low, 8 moderate, 15 high) in 45180 scanned packages
  29 vulnerabilities require manual review. See the full report for details.
```
Thanks
Youssef

### CODE REVIEW

**Comment by sethyates** [comment]
Did you test with these changes?

**Comment by YoussefKaib** [comment]
@sethyates I ran tests locally 

```SUMMARY:
✔ 79 tests completed
ℹ 4 tests skipped

=============================== Coverage summary ===============================
Statements   : 91.17% ( 351/385 ), 15 ignored
Branches     : 85.49% ( 165/193 ), 15 ignored
Functions    : 90.63% ( 58/64 )
Lines        : 89.4% ( 270/302 )
================================================================================
------------------|----------|----------|----------|----------|----------------|
File              |  % Stmts | % Branch |  % Funcs |  % Lines |Uncovered Lines |
------------------|----------|----------|----------|----------|----------------|
 src/             |    91.17 |    85.49 |    90.63 |     89.4 |                |
  postscribe.js   |    85.87 |    82.35 |    81.25 |    83.33 |... 173,174,176 |
  utils.js        |    82.22 |    72.22 |    83.33 |    77.14 |... 78,79,80,82 |
  write-stream.js |    94.76 |    87.94 |    97.22 |    93.53 |... 590,597,598 |
------------------|----------|----------|----------|----------|----------------|
All files         |    91.17 |    85.49 |    90.63 |     89.4 |                |
------------------|----------|----------|----------|----------|----------------|

24 06 2019 15:37:12.196:INFO [coveralls.io]: uploading...
24 06 2019 15:37:12.196:INFO [coveralls.io]: 422 --- {"message":"Couldn't find a repository matching this job.","error":true}
➜  postscribe git:(master) ✗
```

**Comment by sethyates** [comment]
OK well I was going to merge but looks like I've lost write access to the repo.

**Comment by YoussefKaib** [comment]
@sethyates Thanks cc @krux

**Comment by YoussefKaib** [comment]
@sfdc-jd @pkhetrapal friendly following up status on this pr. Ready to be merged?

**Pull request merged**
